# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_id', models.CharField(blank=True, default='', help_text='Human-readable ID, e.g. PAT-2024-0001. Auto-generated if blank.', max_length=30)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('national_id', models.CharField(blank=True, help_text='Encrypted at rest — SSN, national ID, etc.', max_length=100)),
                ('national_id_type', models.CharField(blank=True, help_text="SSN, passport, driver's license, etc.", max_length=50)),
                ('phone_primary', models.CharField(max_length=30)),
                ('phone_secondary', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='US', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_patients', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'patients_patient',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('chronic', 'Chronic Condition'), ('surgery', 'Past Surgery'), ('family', 'Family History'), ('social', 'Social History'), ('trauma', 'Trauma'), ('other', 'Other')], max_length=20)),
                ('condition', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_versions', to='patients.medicalhistory')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'medical histories',
                'db_table': 'patients_medical_history',
                'ordering': ['-onset_date', '-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=200)),
                ('policy_number', models.CharField(max_length=100)),
                ('group_number', models.CharField(blank=True, max_length=100)),
                ('coverage_type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')], default='primary', max_length=20)),
                ('plan_name', models.CharField(blank=True, max_length=200)),
                ('effective_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('card_front_image_url', models.URLField(blank=True)),
                ('card_back_image_url', models.URLField(blank=True)),
                ('policy_holder_name', models.CharField(blank=True, max_length=200)),
                ('policy_holder_relationship', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'insurance policies',
                'db_table': 'patients_insurance_policy',
                'ordering': ['coverage_type', '-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=100)),
                ('phone_primary', models.CharField(max_length=30)),
                ('phone_secondary', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='patients.patient')),
            ],
            options={
                'db_table': 'patients_emergency_contact',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CurrentMedication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('route', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('prescribed_by', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patient')),
            ],
            options={
                'db_table': 'patients_medication',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(choices=[('treatment', 'Treatment Consent'), ('data_sharing', 'Data Sharing'), ('marketing', 'Marketing Communications'), ('research', 'Research Participation'), ('telehealth', 'Telehealth Consent'), ('photography', 'Clinical Photography'), ('other', 'Other')], max_length=30)),
                ('form_name', models.CharField(help_text='Name of the consent form.', max_length=200)),
                ('form_version', models.CharField(help_text='Version of the form when consent was given.', max_length=20)),
                ('status', models.CharField(choices=[('granted', 'Granted'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired'), ('pending', 'Pending')], default='granted', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('granted_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=300)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawal_reason', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consents_granted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='patients.patient')),
            ],
            options={
                'db_table': 'patients_consent',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('substance', models.CharField(max_length=200)),
                ('reaction', models.TextField(blank=True, help_text='Describe the allergic reaction.')),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('life_threatening', 'Life-Threatening')], default='moderate', max_length=20)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('unknown', 'Unknown')], default='active', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patient')),
            ],
            options={
                'db_table': 'patients_allergy',
                'ordering': ['substance'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['tenant'], name='patients_pa_tenant__1713cd_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['tenant', 'last_name', 'first_name'], name='patients_pa_tenant__23a062_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['tenant', 'display_id'], name='patients_pa_tenant__bf599d_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['tenant', 'phone_primary'], name='patients_pa_tenant__22e55a_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['tenant', 'date_of_birth'], name='patients_pa_tenant__9687e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('tenant', 'display_id'), name='unique_display_id_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='medicalhistory',
            index=models.Index(fields=['patient'], name='patients_me_patient_c906c5_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalhistory',
            index=models.Index(fields=['tenant'], name='patients_me_tenant__71b085_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalhistory',
            index=models.Index(fields=['category'], name='patients_me_categor_c47f4e_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['patient'], name='patients_in_patient_70be99_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['tenant'], name='patients_in_tenant__dfbac0_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['policy_number'], name='patients_in_policy__0d9491_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencycontact',
            index=models.Index(fields=['patient'], name='patients_em_patient_b76e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencycontact',
            index=models.Index(fields=['tenant'], name='patients_em_tenant__73d7dc_idx'),
        ),
        migrations.AddIndex(
            model_name='currentmedication',
            index=models.Index(fields=['patient'], name='patients_me_patient_7e6281_idx'),
        ),
        migrations.AddIndex(
            model_name='currentmedication',
            index=models.Index(fields=['tenant'], name='patients_me_tenant__f01559_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['patient'], name='patients_co_patient_027e79_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['tenant'], name='patients_co_tenant__fc1082_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['consent_type', 'status'], name='patients_co_consent_8eeeac_idx'),
        ),
        migrations.AddIndex(
            model_name='allergy',
            index=models.Index(fields=['patient'], name='patients_al_patient_7b9ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='allergy',
            index=models.Index(fields=['tenant'], name='patients_al_tenant__b67956_idx'),
        ),
        migrations.AddIndex(
            model_name='allergy',
            index=models.Index(fields=['severity'], name='patients_al_severit_0b44a8_idx'),
        ),
    ]
