# Generated by Django 6.0.7 on 2026-07-25 13:09

import healthcare_os.utils.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=healthcare_os.utils.encryption.EncryptedCharField(blank=True, help_text='Encrypted at rest (Fernet/AES) — SSN, national ID, etc.', max_length=255),
        ),
    ]
