# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Access to Django admin.')),
                ('is_superuser', models.BooleanField(default=False, help_text='Cross-tenant platform access.')),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_secret', models.CharField(blank=True, help_text='Encrypted TOTP secret.', max_length=255)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('password_reset_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'identity_user',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Label for this key, e.g. 'Patient App Integration'.", max_length=200)),
                ('prefix', models.CharField(help_text='Key prefix for identification: hcos_xxxxxxxx.', max_length=20, unique=True)),
                ('key_hash', models.CharField(help_text='SHA-256 hash of the full key.', max_length=128)),
                ('scopes', models.JSONField(default=list, help_text='List of permission strings: ["patients.read", "appointments.create"].')),
                ('rate_limit', models.CharField(default='100/hour', help_text="Rate limit: '100/hour', '1000/day'.", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'identity_api_key',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_fingerprint', models.CharField(max_length=255)),
                ('device_name', models.CharField(blank=True, max_length=200)),
                ('is_trusted', models.BooleanField(default=False)),
                ('trusted_until', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'identity_device',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codename', models.CharField(help_text="Resource.action format, e.g. 'patients.read'", max_length=120, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.CharField(max_length=300)),
                ('resource', models.CharField(help_text='Resource category: patients, billing, records, etc.', max_length=60)),
                ('action', models.CharField(help_text='Action: read, write, write_demographics, refund, etc.', max_length=60)),
            ],
            options={
                'db_table': 'identity_permission',
                'ordering': ['resource', 'action'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles are templates available to all tenants.')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'identity_role',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_token_jti', models.CharField(help_text='JWT ID of the refresh token.', max_length=255, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=200)),
                ('device_type', models.CharField(blank=True, help_text='web, desktop, mobile', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, help_text='Approximate geo-location (city, country).', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'identity_session',
                'ordering': ['-created_at'],
            },
        ),
    ]
