# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Null for platform super admins.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_api_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apikey',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['resource'], name='identity_pe_resourc_8c415c_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['codename'], name='identity_pe_codenam_f41a8e_idx'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='identity.permission'),
        ),
        migrations.AddField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Null for system roles (templates across tenants).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Primary role determining base permissions.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='identity.role'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Null for super admin sessions.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'device_fingerprint'], name='identity_de_user_id_83e10d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('user', 'device_fingerprint')},
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['tenant'], name='identity_ro_tenant__a54123_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_role_name_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant'], name='identity_us_tenant__aaa22e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant', 'role'], name='identity_us_tenant__ce22b9_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user'], name='identity_se_user_id_aec763_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['refresh_token_jti'], name='identity_se_refresh_b00dd7_idx'),
        ),
    ]
