# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BPReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('systolic', models.IntegerField()),
                ('diastolic', models.IntegerField()),
                ('pulse', models.IntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cardio_bp',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='CVRiskScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_type', models.CharField(choices=[('framingham', 'Framingham'), ('ascvd', 'ASCVD')], default='ascvd', max_length=30)),
                ('risk_percentage', models.DecimalField(decimal_places=1, help_text='10-year risk %.', max_digits=5)),
                ('risk_category', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20)),
                ('calculated_date', models.DateField(default=django.utils.timezone.localdate)),
                ('factors', models.JSONField(default=dict, help_text='Age, sex, total cholesterol, HDL, systolic BP, treated, smoker, diabetes.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cardio_risk',
                'ordering': ['-calculated_date'],
            },
        ),
        migrations.CreateModel(
            name='ECGRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('performed_date', models.DateField(default=django.utils.timezone.localdate)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('rhythm', models.CharField(blank=True, help_text='Sinus, AFib, etc.', max_length=100)),
                ('pr_interval', models.IntegerField(blank=True, help_text='ms', null=True)),
                ('qrs_duration', models.IntegerField(blank=True, help_text='ms', null=True)),
                ('qt_interval', models.IntegerField(blank=True, help_text='ms', null=True)),
                ('findings', models.TextField(blank=True)),
                ('interpretation', models.TextField(blank=True)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('file_path', models.CharField(blank=True, help_text='ECG waveform file.', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cardio_ecg',
                'ordering': ['-performed_date'],
            },
        ),
        migrations.CreateModel(
            name='EchoReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('study_date', models.DateField(default=django.utils.timezone.localdate)),
                ('lvef', models.IntegerField(blank=True, help_text='LV ejection fraction %.', null=True)),
                ('lv_ed_diameter', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('la_diameter', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('rv_function', models.CharField(blank=True, max_length=50)),
                ('valve_findings', models.TextField(blank=True)),
                ('findings', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cardio_echo',
                'ordering': ['-study_date'],
            },
        ),
    ]
