# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cardiology', '0001_initial'),
        ('patients', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bpreading',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_readings', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='bpreading',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_readings', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='cvriskscore',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_risk_scores', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='cvriskscore',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_risk_scores', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='ecgrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecg_records', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='ecgrecord',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ecgrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecg_records', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='echoreport',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echo_reports', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='echoreport',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='echoreport',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echo_reports', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='bpreading',
            index=models.Index(fields=['patient'], name='cardio_bp_patient_6f49f3_idx'),
        ),
        migrations.AddIndex(
            model_name='bpreading',
            index=models.Index(fields=['recorded_at'], name='cardio_bp_recorde_d83fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='ecgrecord',
            index=models.Index(fields=['patient'], name='cardio_ecg_patient_9b47ab_idx'),
        ),
        migrations.AddIndex(
            model_name='ecgrecord',
            index=models.Index(fields=['is_abnormal'], name='cardio_ecg_is_abno_b10ec8_idx'),
        ),
    ]
