# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FractureRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bone', models.CharField(max_length=200)),
                ('fracture_type', models.CharField(help_text='Simple, compound, comminuted, greenstick, etc.', max_length=100)),
                ('classification', models.CharField(blank=True, max_length=100)),
                ('side', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=10)),
                ('diagnosis_date', models.DateField(default=django.utils.timezone.localdate)),
                ('treatment', models.TextField(blank=True, help_text='Cast, splint, surgery, etc.')),
                ('healing_status', models.CharField(choices=[('acute', 'Acute'), ('healing', 'Healing'), ('healed', 'Healed'), ('non_union', 'Non-Union'), ('malunion', 'Malunion')], default='acute', max_length=50)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fracture_records', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fracture_records', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'ortho_fracture',
                'ordering': ['-diagnosis_date'],
            },
        ),
        migrations.CreateModel(
            name='JointAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joint', models.CharField(choices=[('shoulder', 'Shoulder'), ('elbow', 'Elbow'), ('wrist', 'Wrist'), ('hip', 'Hip'), ('knee', 'Knee'), ('ankle', 'Ankle'), ('spine', 'Spine'), ('other', 'Other')], max_length=50)),
                ('side', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('bilateral', 'Bilateral')], max_length=10)),
                ('assessment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('range_of_motion', models.CharField(blank=True, help_text='Degrees or description.', max_length=100)),
                ('strength_grade', models.IntegerField(blank=True, help_text='0-5 MRC scale.', null=True)),
                ('stability', models.CharField(blank=True, max_length=100)),
                ('pain_level', models.IntegerField(blank=True, help_text='0-10.', null=True)),
                ('special_tests', models.TextField(blank=True)),
                ('findings', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joint_assessments', to='patients.patient')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joint_assessments', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'ortho_joint',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='PhysiotherapyPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('condition', models.CharField(blank=True, max_length=300)),
                ('exercises', models.JSONField(default=list, help_text='[{"name":"","sets":3,"reps":10,"frequency":"daily","notes":""}]')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_plans', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_plans', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'ortho_physio',
                'ordering': ['-start_date'],
            },
        ),
    ]
