# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_provider', models.CharField(default='smtp', max_length=50)),
                ('email_from_address', models.EmailField(default='noreply@healthcare-os.com', max_length=254)),
                ('email_from_name', models.CharField(default='Healthcare OS', max_length=100)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_provider', models.CharField(blank=True, help_text='twilio, vonage, custom', max_length=50)),
                ('sms_from_number', models.CharField(blank=True, max_length=20)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('whatsapp_from_number', models.CharField(blank=True, max_length=20)),
                ('push_enabled', models.BooleanField(default=False)),
                ('max_sms_per_day', models.IntegerField(default=100)),
                ('max_email_per_hour', models.IntegerField(default=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_config', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'notifications_channel_config',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('appointment_scheduled', 'Appointment Scheduled'), ('appointment_reminder', 'Appointment Reminder'), ('appointment_cancelled', 'Appointment Cancelled'), ('missed_appointment', 'Missed Appointment'), ('invoice_issued', 'Invoice Issued'), ('payment_received', 'Payment Received'), ('payment_overdue', 'Payment Overdue'), ('result_ready', 'Lab Result Ready'), ('follow_up_due', 'Follow-Up Due'), ('prescription_ready', 'Prescription Ready'), ('stock_below_threshold', 'Stock Below Threshold'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification')], max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Email subject line.', max_length=300)),
                ('body_text', models.TextField(blank=True, help_text='Plain text version.')),
                ('body_html', models.TextField(blank=True, help_text='HTML version (email/WhatsApp).')),
                ('available_variables', models.JSONField(default=list, help_text='List of variable names: ["patient_name", "appointment_time", ...]')),
                ('language', models.CharField(default='en', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Null for system-wide default templates.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'notifications_template',
                'ordering': ['event_type', 'channel'],
            },
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('appointment_scheduled', 'Appointment Scheduled'), ('appointment_reminder', 'Appointment Reminder'), ('appointment_cancelled', 'Appointment Cancelled'), ('missed_appointment', 'Missed Appointment'), ('invoice_issued', 'Invoice Issued'), ('payment_received', 'Payment Received'), ('payment_overdue', 'Payment Overdue'), ('result_ready', 'Lab Result Ready'), ('follow_up_due', 'Follow-Up Due'), ('prescription_ready', 'Prescription Ready'), ('stock_below_threshold', 'Stock Below Threshold'), ('custom', 'Custom')], max_length=50)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification')], max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=30)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to='tenancy.tenant')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='notifications.notificationtemplate')),
            ],
            options={
                'db_table': 'notifications_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='notificationtemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'event_type', 'channel', 'language'), name='unique_template_per_tenant_event_channel_lang'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['tenant'], name='notificatio_tenant__2cb4ab_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['tenant', 'event_type'], name='notificatio_tenant__07e56c_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['tenant', 'status'], name='notificatio_tenant__98ef97_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['recipient_user'], name='notificatio_recipie_82acdf_idx'),
        ),
    ]
