# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icd_code', models.CharField(help_text='ICD-10 code, e.g. J45.909', max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('diagnosis_type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('admitting', 'Admitting'), ('discharge', 'Discharge')], default='primary', max_length=20)),
                ('is_chronic', models.BooleanField(default=False)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clinical_diagnosis',
                'ordering': ['diagnosis_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subjective', models.TextField(blank=True, help_text='Chief complaint, history of present illness.')),
                ('objective', models.TextField(blank=True, help_text='Physical exam findings, vitals summary.')),
                ('assessment', models.TextField(blank=True, help_text='Diagnosis, differential, clinical impression.')),
                ('plan', models.TextField(blank=True, help_text='Treatment plan, orders, follow-up.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('finalized', 'Finalized'), ('signed', 'Signed'), ('amended', 'Amended')], default='draft', max_length=15)),
                ('encounter_date', models.DateField(default=django.utils.timezone.localdate)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clinical_encounter',
                'ordering': ['-encounter_date'],
            },
        ),
        migrations.CreateModel(
            name='FamilyHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship', models.CharField(help_text='e.g. Mother, Father, Sibling', max_length=100)),
                ('condition', models.CharField(max_length=300)),
                ('age_at_onset', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('living', 'Living'), ('deceased', 'Deceased')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clinical_family_history',
                'ordering': ['relationship'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialist_name', models.CharField(max_length=200)),
                ('specialty', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clinical_referral',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('smoking_status', models.CharField(choices=[('never', 'Never'), ('former', 'Former'), ('current', 'Current'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('alcohol_use', models.CharField(choices=[('none', 'None'), ('occasional', 'Occasional'), ('moderate', 'Moderate'), ('heavy', 'Heavy'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('exercise_frequency', models.CharField(choices=[('none', 'None'), ('occasional', 'Occasional'), ('regular', 'Regular'), ('daily', 'Daily'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('diet_description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'social histories',
                'db_table': 'clinical_social_history',
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=300)),
                ('dose_number', models.IntegerField(default=1)),
                ('lot_number', models.CharField(blank=True, max_length=100)),
                ('administration_site', models.CharField(blank=True, help_text='e.g. Left deltoid', max_length=100)),
                ('administered_date', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clinical_vaccination',
                'ordering': ['-administered_date'],
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('systolic_bp', models.IntegerField(blank=True, null=True)),
                ('diastolic_bp', models.IntegerField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('oxygen_saturation', models.IntegerField(blank=True, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, help_text='Auto-calculated.', max_digits=5, null=True)),
                ('pain_score', models.IntegerField(blank=True, help_text='0-10 scale.', null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'clinical_vitals',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
