# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        ('patients', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounter', to='scheduling.appointment'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='practitioner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encounter',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_encounters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encounter',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='clinical.encounter'),
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_history', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_history', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='referral',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='clinical.encounter'),
        ),
        migrations.AddField(
            model_name='referral',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referring_practitioner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referrals_out', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_history', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='socialhistory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_history', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='administered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='clinical.encounter'),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vitalsigns',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['tenant'], name='clinical_en_tenant__a86754_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient'], name='clinical_en_patient_c5f552_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['status'], name='clinical_en_status_fcc7c5_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['patient'], name='clinical_di_patient_4a2618_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['icd_code'], name='clinical_di_icd_cod_d63d7b_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['patient'], name='clinical_re_patient_aba369_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['status'], name='clinical_re_status_beec74_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalsigns',
            index=models.Index(fields=['patient'], name='clinical_vi_patient_c95a06_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalsigns',
            index=models.Index(fields=['recorded_at'], name='clinical_vi_recorde_529e20_idx'),
        ),
    ]
