# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('patients', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billingitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_items', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='insurance_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='patients.insurancepolicy'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_claims', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claims', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_claims', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='original_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='quote',
            name='converted_invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quote', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='quote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='quote',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='billingitem',
            index=models.Index(fields=['tenant'], name='billing_ite_tenant__6252d6_idx'),
        ),
        migrations.AddIndex(
            model_name='billingitem',
            index=models.Index(fields=['tenant', 'category'], name='billing_ite_tenant__775814_idx'),
        ),
        migrations.AddIndex(
            model_name='billingitem',
            index=models.Index(fields=['tenant', 'is_active'], name='billing_ite_tenant__5dbf64_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant'], name='billing_inv_tenant__2244b8_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'patient'], name='billing_inv_tenant__293ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'status'], name='billing_inv_tenant__f82d44_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'invoice_number'], name='billing_inv_tenant__a731bc_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'due_date'], name='billing_inv_tenant__0b515c_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(fields=['tenant'], name='billing_ins_tenant__09d6a8_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(fields=['tenant', 'patient'], name='billing_ins_tenant__4a2a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(fields=['tenant', 'status'], name='billing_ins_tenant__594aa5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant'], name='billing_pay_tenant__830232_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'patient'], name='billing_pay_tenant__06307d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'method'], name='billing_pay_tenant__22dd37_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'payment_date'], name='billing_pay_tenant__afafe2_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['tenant'], name='billing_quo_tenant__ced72b_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['tenant', 'patient'], name='billing_quo_tenant__bac4d5_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['tenant', 'status'], name='billing_quo_tenant__2918f8_idx'),
        ),
    ]
