# Generated by Django 6.0.7 on 2026-07-25 10:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FHIRAppRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=200, unique=True)),
                ('client_secret', models.CharField(blank=True, max_length=500)),
                ('app_name', models.CharField(max_length=300)),
                ('redirect_uris', models.JSONField(default=list)),
                ('scopes', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fhir_app_registration',
            },
        ),
        migrations.CreateModel(
            name='SMARTonFHIRConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('issuer_url', models.URLField(blank=True, help_text='FHIR base URL, e.g. https://app.healthcare-os.com/fhir')),
                ('authorization_endpoint', models.URLField(blank=True)),
                ('token_endpoint', models.URLField(blank=True)),
                ('supported_scopes', models.JSONField(default=list, help_text='["patient/*.read","launch/patient"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fhir_smart_config',
            },
        ),
    ]
