# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fhir', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhirappregistration',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fhir_apps', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='smartonfhirconfig',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_configs', to='tenancy.tenant'),
        ),
    ]
