# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('series_uid', models.CharField(blank=True, help_text='DICOM Series Instance UID.', max_length=200)),
                ('series_number', models.IntegerField(default=1)),
                ('modality', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('body_part', models.CharField(blank=True, max_length=200)),
                ('image_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'verbose_name_plural': 'imaging series',
                'db_table': 'imaging_series',
                'ordering': ['series_number'],
            },
        ),
        migrations.CreateModel(
            name='ImagingImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sop_instance_uid', models.CharField(blank=True, help_text='DICOM SOP Instance UID.', max_length=200)),
                ('image_number', models.IntegerField(default=1)),
                ('file_path', models.CharField(blank=True, help_text='Object storage path.', max_length=1000)),
                ('mime_type', models.CharField(default='application/dicom', max_length=50)),
                ('file_size', models.BigIntegerField(default=0)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('slice_location', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('window_center', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('window_width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='imaging.imagingseries')),
            ],
            options={
                'db_table': 'imaging_image',
                'ordering': ['image_number'],
            },
        ),
        migrations.CreateModel(
            name='ImagingStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('study_uid', models.CharField(blank=True, help_text='DICOM Study Instance UID.', max_length=200, unique=True)),
                ('accession_number', models.CharField(blank=True, max_length=100)),
                ('modality', models.CharField(choices=[('xray', 'X-Ray'), ('ct', 'CT Scan'), ('mri', 'MRI'), ('ultrasound', 'Ultrasound'), ('mammography', 'Mammography'), ('nuclear', 'Nuclear Medicine'), ('dexa', 'DEXA / Bone Density'), ('other', 'Other')], max_length=20)),
                ('body_part', models.CharField(blank=True, help_text='e.g. Chest, Brain, Left Knee', max_length=200)),
                ('protocol', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('performed', 'Performed'), ('reporting', 'Reporting'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Clinical indication for the study.')),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.appointment')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordered_studies', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imaging_studies', to='patients.patient')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performed_studies', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_studies', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'imaging_study',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='imagingseries',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='imaging.imagingstudy'),
        ),
        migrations.CreateModel(
            name='RadiologyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('findings', models.TextField(blank=True, help_text='Detailed imaging findings.')),
                ('impression', models.TextField(blank=True, help_text='Summary impression / conclusion.')),
                ('recommendations', models.TextField(blank=True, help_text='Follow-up recommendations.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('dictated', 'Dictated'), ('transcribed', 'Transcribed'), ('reviewed', 'Reviewed'), ('signed', 'Signed'), ('amended', 'Amended')], default='draft', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='radiology_reports', to=settings.AUTH_USER_MODEL)),
                ('comparison_study', models.ForeignKey(blank=True, help_text='Prior study for comparison.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compared_reports', to='imaging.imagingstudy')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_reports', to=settings.AUTH_USER_MODEL)),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='imaging.imagingstudy')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiology_reports', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'imaging_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='imagingstudy',
            index=models.Index(fields=['tenant'], name='imaging_stu_tenant__7f56a0_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingstudy',
            index=models.Index(fields=['patient'], name='imaging_stu_patient_0c4cb5_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingstudy',
            index=models.Index(fields=['modality'], name='imaging_stu_modalit_2241d0_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingstudy',
            index=models.Index(fields=['status'], name='imaging_stu_status_564f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingstudy',
            index=models.Index(fields=['study_uid'], name='imaging_stu_study_u_d9b006_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyreport',
            index=models.Index(fields=['tenant'], name='imaging_rep_tenant__cd69d4_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyreport',
            index=models.Index(fields=['study'], name='imaging_rep_study_i_8b30b5_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyreport',
            index=models.Index(fields=['status'], name='imaging_rep_status_8bbd73_idx'),
        ),
    ]
