# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntenatalVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('gestational_weeks', models.IntegerField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('bp_systolic', models.IntegerField(blank=True, null=True)),
                ('bp_diastolic', models.IntegerField(blank=True, null=True)),
                ('fundal_height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fetal_hr', models.IntegerField(blank=True, null=True)),
                ('fetal_movement', models.BooleanField(null=True)),
                ('ultrasound_findings', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gyn_antenatal',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='OBHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gravida', models.IntegerField(default=0, help_text='Total pregnancies.')),
                ('para', models.IntegerField(default=0, help_text='Pregnancies carried past 20 weeks.')),
                ('abortus', models.IntegerField(default=0, help_text='Pregnancy losses before 20 weeks.')),
                ('lmp', models.DateField(blank=True, help_text='Last menstrual period.', null=True)),
                ('edd', models.DateField(blank=True, help_text='Estimated due date.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'OB histories',
                'db_table': 'gyn_ob_history',
            },
        ),
        migrations.CreateModel(
            name='PapSmear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('performed_date', models.DateField(default=django.utils.timezone.localdate)),
                ('result', models.CharField(choices=[('normal', 'Normal'), ('ascus', 'ASC-US'), ('lsil', 'LSIL'), ('hsil', 'HSIL'), ('agc', 'AGC'), ('other', 'Other')], max_length=50)),
                ('hpv_co_test', models.BooleanField(default=False)),
                ('hpv_positive', models.BooleanField(blank=True, null=True)),
                ('follow_up_recommended', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gyn_pap',
                'ordering': ['-performed_date'],
            },
        ),
    ]
