# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gynecology', '0001_initial'),
        ('patients', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='antenatalvisit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antenatal_visits', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='antenatalvisit',
            name='practitioner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='antenatalvisit',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antenatal_visits', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='obhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ob_histories', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='obhistory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ob_histories', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='papsmear',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pap_smears', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='papsmear',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='papsmear',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pap_smears', to='tenancy.tenant'),
        ),
    ]
