# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerStaging',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis', models.CharField(help_text='Cancer type.', max_length=300)),
                ('tnm_t', models.CharField(blank=True, max_length=10)),
                ('tnm_n', models.CharField(blank=True, max_length=10)),
                ('tnm_m', models.CharField(blank=True, max_length=10)),
                ('stage', models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=10)),
                ('diagnosis_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancer_stagings', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancer_stagings', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'onc_staging',
                'ordering': ['-diagnosis_date'],
            },
        ),
        migrations.CreateModel(
            name='ChemotherapyProtocol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('protocol_name', models.CharField(max_length=300)),
                ('drugs', models.JSONField(default=list, help_text='[{"name":"","dose":"","unit":"mg/m2"}]')),
                ('cycle_number', models.IntegerField(default=1)),
                ('total_cycles', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('discontinued', 'Discontinued')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemo_protocols', to='patients.patient')),
                ('prescribed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemo_protocols', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'onc_chemo',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TumorMarker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marker_name', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=100)),
                ('measured_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tumor_markers', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tumor_markers', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'onc_marker',
                'ordering': ['-measured_date'],
            },
        ),
    ]
