# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('species', models.CharField(choices=[('canine', 'Canine'), ('feline', 'Feline'), ('equine', 'Equine'), ('bovine', 'Bovine'), ('avian', 'Avian'), ('other', 'Other')], max_length=50)),
                ('breed', models.CharField(blank=True, max_length=200)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('male_neutered', 'Male Neutered'), ('female_spayed', 'Female Spayed')], max_length=20)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('microchip_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='animal_record', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_records', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'vet_animal',
            },
        ),
        migrations.CreateModel(
            name='RabiesCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=200)),
                ('lot_number', models.CharField(blank=True, max_length=100)),
                ('administered_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expiration_date', models.DateField()),
                ('veterinarian', models.CharField(blank=True, max_length=200)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rabies_certs', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rabies_certs', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'vet_rabies',
                'ordering': ['-administered_date'],
            },
        ),
    ]
