# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DialysisSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateField(default=django.utils.timezone.localdate)),
                ('dialysis_type', models.CharField(choices=[('hemodialysis', 'Hemodialysis'), ('peritoneal', 'Peritoneal')], default='hemodialysis', max_length=20)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('pre_weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('post_weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fluid_removed_ml', models.IntegerField(blank=True, null=True)),
                ('pre_bp_systolic', models.IntegerField(blank=True, null=True)),
                ('pre_bp_diastolic', models.IntegerField(blank=True, null=True)),
                ('post_bp_systolic', models.IntegerField(blank=True, null=True)),
                ('post_bp_diastolic', models.IntegerField(blank=True, null=True)),
                ('access_site', models.CharField(blank=True, help_text='AV fistula, graft, catheter site.', max_length=200)),
                ('access_site_condition', models.CharField(blank=True, max_length=100)),
                ('complications', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dialysis_session',
                'ordering': ['-session_date'],
            },
        ),
    ]
