# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dialysis', '0001_initial'),
        ('patients', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dialysissession',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialysis_sessions', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='dialysissession',
            name='practitioner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dialysissession',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialysis_sessions', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='dialysissession',
            index=models.Index(fields=['patient'], name='dialysis_se_patient_2e4239_idx'),
        ),
        migrations.AddIndex(
            model_name='dialysissession',
            index=models.Index(fields=['session_date'], name='dialysis_se_session_29f1f2_idx'),
        ),
    ]
