# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'modules_installation',
            },
        ),
        migrations.CreateModel(
            name='DentalTreatmentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('presented', 'Presented to Patient'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('declined', 'Declined')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('estimated_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('insurance_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('patient_portion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('consent_signed', models.BooleanField(default=False)),
                ('consent_signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dental_plans', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_plans', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_plans', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'dental_treatment_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fdi_number', models.IntegerField(help_text='FDI tooth number (11-48 permanent, 51-85 primary).')),
                ('condition', models.CharField(choices=[('healthy', 'Healthy'), ('filled', 'Filled'), ('decayed', 'Decayed'), ('crowned', 'Crowned'), ('missing', 'Missing'), ('implant', 'Implant'), ('bridge', 'Bridge Abutment'), ('root_canal', 'Root Canal Treated'), ('veneer', 'Veneer'), ('fractured', 'Fractured'), ('abscess', 'Abscess'), ('other', 'Other')], default='healthy', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('surface_data', models.JSONField(blank=True, default=dict, help_text="Per-surface conditions: {'mesial': 'decayed', 'occlusal': 'filled', ...}")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'dental_tooth',
                'ordering': ['fdi_number'],
            },
        ),
        migrations.CreateModel(
            name='Implant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('diameter_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('length_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('placement_date', models.DateField()),
                ('restoration_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implants', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
                ('tooth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='implant', to='modules.tooth')),
            ],
            options={
                'db_table': 'dental_implant',
            },
        ),
        migrations.CreateModel(
            name='Crown',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material', models.CharField(choices=[('pfm', 'Porcelain-Fused-to-Metal'), ('zirconia', 'Zirconia'), ('emax', 'E-Max (Lithium Disilicate)'), ('full_metal', 'Full Metal'), ('gold', 'Gold'), ('other', 'Other')], default='zirconia', max_length=20)),
                ('prep_date', models.DateField()),
                ('cementation_date', models.DateField(blank=True, null=True)),
                ('lab_name', models.CharField(blank=True, max_length=200)),
                ('lab_tracking', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowns', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
                ('tooth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crown', to='modules.tooth')),
            ],
            options={
                'db_table': 'dental_crown',
            },
        ),
        migrations.CreateModel(
            name='ToothChart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_chart', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_charts', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'dental_tooth_chart',
            },
        ),
        migrations.AddField(
            model_name='tooth',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teeth', to='modules.toothchart'),
        ),
        migrations.CreateModel(
            name='ToothProcedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('procedure_type', models.CharField(choices=[('filling_composite', 'Composite Filling'), ('filling_amalgam', 'Amalgam Filling'), ('extraction', 'Extraction'), ('root_canal', 'Root Canal Treatment'), ('crown_prep', 'Crown Preparation'), ('crown_cement', 'Crown Cementation'), ('implant_placement', 'Implant Placement'), ('veneer', 'Veneer'), ('bridge', 'Bridge'), ('scaling', 'Scaling & Root Planing'), ('whitening', 'Whitening'), ('exam', 'Examination'), ('xray', 'X-Ray'), ('other', 'Other')], max_length=30)),
                ('surfaces', models.JSONField(blank=True, default=list, help_text="Surfaces treated: ['mesial', 'occlusal', 'distal', 'buccal', 'lingual']")),
                ('description', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('materials', models.JSONField(blank=True, default=list, help_text='Materials used in the procedure.')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dental_procedures', to='scheduling.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_procedures', to='patients.patient')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dental_procedures', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
                ('tooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='modules.tooth')),
            ],
            options={
                'db_table': 'dental_procedure',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlanPhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='modules.dentaltreatmentplan')),
            ],
            options={
                'db_table': 'dental_treatment_phase',
                'ordering': ['plan', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PlannedProcedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('procedure_type', models.CharField(choices=[('filling_composite', 'Composite Filling'), ('filling_amalgam', 'Amalgam Filling'), ('extraction', 'Extraction'), ('root_canal', 'Root Canal Treatment'), ('crown_prep', 'Crown Preparation'), ('crown_cement', 'Crown Cementation'), ('implant_placement', 'Implant Placement'), ('veneer', 'Veneer'), ('bridge', 'Bridge'), ('scaling', 'Scaling & Root Planing'), ('whitening', 'Whitening'), ('exam', 'Examination'), ('xray', 'X-Ray'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=10)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tooth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planned_procedures', to='modules.tooth')),
                ('completed_procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_plan', to='modules.toothprocedure')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='modules.treatmentplanphase')),
            ],
            options={
                'db_table': 'dental_planned_procedure',
                'ordering': ['phase', 'priority', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dentaltreatmentplan',
            index=models.Index(fields=['tenant'], name='dental_trea_tenant__eac020_idx'),
        ),
        migrations.AddIndex(
            model_name='dentaltreatmentplan',
            index=models.Index(fields=['patient'], name='dental_trea_patient_0f6e19_idx'),
        ),
        migrations.AddIndex(
            model_name='dentaltreatmentplan',
            index=models.Index(fields=['status'], name='dental_trea_status_58f03e_idx'),
        ),
        migrations.AddIndex(
            model_name='implant',
            index=models.Index(fields=['patient'], name='dental_impl_patient_b6077a_idx'),
        ),
        migrations.AddIndex(
            model_name='crown',
            index=models.Index(fields=['patient'], name='dental_crow_patient_9c4dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='tooth',
            index=models.Index(fields=['chart'], name='dental_toot_chart_i_afbdef_idx'),
        ),
        migrations.AddIndex(
            model_name='tooth',
            index=models.Index(fields=['tenant'], name='dental_toot_tenant__b0e6ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tooth',
            unique_together={('chart', 'fdi_number')},
        ),
        migrations.AddIndex(
            model_name='toothprocedure',
            index=models.Index(fields=['tooth'], name='dental_proc_tooth_i_1f2f35_idx'),
        ),
        migrations.AddIndex(
            model_name='toothprocedure',
            index=models.Index(fields=['patient'], name='dental_proc_patient_91d8b0_idx'),
        ),
        migrations.AddIndex(
            model_name='toothprocedure',
            index=models.Index(fields=['tenant'], name='dental_proc_tenant__d10640_idx'),
        ),
    ]
