# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_name', models.CharField(help_text="e.g. 'Front Desk PC'.", max_length=200)),
                ('device_id', models.CharField(help_text='Hardware/install UUID.', max_length=100, unique=True)),
                ('platform', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')], default='desktop', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_cursor', models.CharField(blank=True, help_text='Last synced event timestamp/cursor for pull.', max_length=100)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'sync_device',
            },
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_pull_cursor', models.CharField(blank=True, max_length=100)),
                ('last_push_sequence', models.BigIntegerField(default=0)),
                ('pending_count', models.IntegerField(default=0)),
                ('conflict_count', models.IntegerField(default=0)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_success', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_state', to='sync.deviceregistration')),
            ],
            options={
                'db_table': 'sync_state',
            },
        ),
        migrations.CreateModel(
            name='ConflictResolutionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=100)),
                ('strategy', models.CharField(choices=[('last_write_wins', 'Last Write Wins'), ('client_wins', 'Client Wins'), ('server_wins', 'Server Wins'), ('merge', 'Auto-Merge'), ('manual', 'Manual Review')], default='manual', max_length=20)),
                ('merge_safe_fields', models.JSONField(default=list, help_text='Fields safe to auto-merge. Only used with MERGE strategy.')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_rules', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'sync_conflict_rule',
                'unique_together': {('tenant', 'entity_type')},
            },
        ),
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(db_index=True, max_length=100)),
                ('entity_id', models.CharField(db_index=True, max_length=100)),
                ('operation_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('payload', models.JSONField(default=dict, help_text='Full or diff payload.')),
                ('base_version', models.IntegerField(default=0, help_text='Version the client thinks the record is at. Used for conflict detection.')),
                ('client_timestamp', models.DateTimeField(help_text='When this operation was created on the client.')),
                ('sequence_number', models.BigIntegerField(help_text='Monotonic sequence from the client device.')),
                ('dependencies', models.JSONField(default=list, help_text='List of operation IDs that must be processed first.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('conflict', 'Conflict'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=5)),
                ('last_error', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Client-generated UUID. Replaying this key is safe.', max_length=100, unique=True)),
                ('server_timestamp', models.DateTimeField(blank=True, null=True)),
                ('server_version', models.IntegerField(blank=True, null=True)),
                ('conflict_info', models.JSONField(blank=True, help_text='Conflict details if status=conflict.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='sync.deviceregistration')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_operations', to='tenancy.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sync_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_operation',
                'ordering': ['sequence_number'],
                'indexes': [models.Index(fields=['tenant', 'device'], name='sync_operat_tenant__c265d6_idx'), models.Index(fields=['tenant', 'entity_type', 'entity_id'], name='sync_operat_tenant__49250a_idx'), models.Index(fields=['tenant', 'status'], name='sync_operat_tenant__75961b_idx'), models.Index(fields=['idempotency_key'], name='sync_operat_idempot_79b91b_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'sequence_number'), name='unique_device_sequence')],
            },
        ),
    ]
