# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('collected', 'Specimen Collected'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ordered', max_length=20)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.appointment')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'lab_order',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(db_index=True, max_length=100, unique=True)),
                ('specimen_type', models.CharField(max_length=100)),
                ('collection_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('received', 'Received at Lab'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='collected', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collected_specimens', to=settings.AUTH_USER_MODEL)),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='laboratory.laborder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'lab_specimen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(choices=[('hematology', 'Hematology'), ('chemistry', 'Clinical Chemistry'), ('microbiology', 'Microbiology'), ('immunology', 'Immunology'), ('pathology', 'Pathology'), ('urinalysis', 'Urinalysis'), ('other', 'Other')], default='chemistry', max_length=20)),
                ('specimen_type', models.CharField(help_text='Blood, urine, swab, etc.', max_length=100)),
                ('unit', models.CharField(blank=True, help_text='mg/dL, mm/hr, etc.', max_length=50)),
                ('reference_range_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reference_range_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reference_range_text', models.CharField(blank=True, help_text='For non-numeric ranges.', max_length=200)),
                ('turnaround_minutes', models.IntegerField(default=60, help_text='Expected turnaround time.')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'lab_test_catalog',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('value_text', models.CharField(blank=True, help_text='For qualitative results.', max_length=500)),
                ('flag', models.CharField(choices=[('normal', 'Normal'), ('low', 'Below Range'), ('high', 'Above Range'), ('critical_low', 'Critical Low'), ('critical_high', 'Critical High'), ('abnormal', 'Abnormal')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('amended', 'Amended')], default='draft', max_length=15)),
                ('is_critical', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_results', to=settings.AUTH_USER_MODEL)),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='laboratory.laborder')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_results', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_results', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='tenancy.tenant')),
                ('specimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='laboratory.specimen')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='laboratory.testcatalog')),
            ],
            options={
                'db_table': 'lab_result',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddField(
            model_name='laborder',
            name='tests',
            field=models.ManyToManyField(related_name='orders', to='laboratory.testcatalog'),
        ),
        migrations.AddIndex(
            model_name='specimen',
            index=models.Index(fields=['barcode'], name='lab_specime_barcode_71e5d0_idx'),
        ),
        migrations.AddIndex(
            model_name='specimen',
            index=models.Index(fields=['tenant'], name='lab_specime_tenant__7a9799_idx'),
        ),
        migrations.AddConstraint(
            model_name='testcatalog',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_lab_test_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['tenant'], name='lab_result_tenant__df0c4f_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['lab_order'], name='lab_result_lab_ord_8b9307_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['flag'], name='lab_result_flag_9c1339_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['tenant'], name='lab_order_tenant__62f718_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['patient'], name='lab_order_patient_c26b34_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['status'], name='lab_order_status_9138cf_idx'),
        ),
    ]
