# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(editable=False, help_text='Auto-calculated from start/end.')),
                ('type', models.CharField(choices=[('consultation', 'Consultation'), ('follow_up', 'Follow-Up'), ('procedure', 'Procedure'), ('emergency', 'Emergency'), ('checkup', 'Checkup'), ('other', 'Other')], default='consultation', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('arrived', 'Arrived'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='scheduled', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Chief complaint or reason for visit.')),
                ('notes', models.TextField(blank=True, help_text='Internal notes (not shared with patient).')),
                ('color', models.CharField(blank=True, help_text='Override color for calendar display.', max_length=7)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_rule', models.CharField(blank=True, help_text='RRULE string for recurring appointments.', max_length=500)),
                ('recurrence_group', models.UUIDField(blank=True, help_text='Shared UUID for all instances of a recurring series.', null=True)),
                ('is_recurrence_exception', models.BooleanField(default=False, help_text='True if this instance was modified from the recurrence pattern.')),
                ('booked_online', models.BooleanField(default=False)),
                ('booking_source', models.CharField(blank=True, help_text='web, phone, walk-in, app.', max_length=50)),
                ('confirmation_code', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'scheduling_appointment',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='BookingToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('action', models.CharField(choices=[('confirm', 'Confirm'), ('cancel', 'Cancel'), ('reschedule', 'Reschedule')], max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_tokens', to='scheduling.appointment')),
            ],
            options={
                'db_table': 'scheduling_booking_token',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6b7280', help_text='Hex color for calendar.', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'scheduling_room',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PractitionerSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration_minutes', models.IntegerField(default=30, help_text='Duration of each bookable slot.')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_schedules', to='tenancy.tenant')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='scheduling.room')),
            ],
            options={
                'db_table': 'scheduling_practitioner_schedule',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='scheduling.room'),
        ),
        migrations.CreateModel(
            name='WaitingListEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_date_start', models.DateField(blank=True, null=True)),
                ('preferred_date_end', models.DateField(blank=True, null=True)),
                ('preferred_time_of_day', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=20)),
                ('appointment_type', models.CharField(choices=[('consultation', 'Consultation'), ('follow_up', 'Follow-Up'), ('procedure', 'Procedure'), ('emergency', 'Emergency'), ('checkup', 'Checkup'), ('other', 'Other')], default='consultation', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fulfilled_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_waiting_entry', to='scheduling.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list_entries', to='patients.patient')),
                ('preferred_practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiting_list_entries', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list', to='tenancy.tenant')),
            ],
            options={
                'verbose_name_plural': 'waiting list entries',
                'db_table': 'scheduling_waiting_list',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_room_name_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='practitionerschedule',
            index=models.Index(fields=['tenant', 'practitioner'], name='scheduling__tenant__b5642d_idx'),
        ),
        migrations.AddIndex(
            model_name='practitionerschedule',
            index=models.Index(fields=['tenant', 'day_of_week'], name='scheduling__tenant__76e0b6_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'start_time'], name='scheduling__tenant__0b2d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'patient'], name='scheduling__tenant__940561_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'practitioner'], name='scheduling__tenant__881198_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'status'], name='scheduling__tenant__ea90db_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'start_time', 'end_time'], name='scheduling__tenant__a7f939_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='appointment_start_before_end'),
        ),
        migrations.AddIndex(
            model_name='waitinglistentry',
            index=models.Index(fields=['tenant'], name='scheduling__tenant__d47d7a_idx'),
        ),
        migrations.AddIndex(
            model_name='waitinglistentry',
            index=models.Index(fields=['tenant', 'is_fulfilled'], name='scheduling__tenant__bce77a_idx'),
        ),
        migrations.AddIndex(
            model_name='waitinglistentry',
            index=models.Index(fields=['tenant', 'priority'], name='scheduling__tenant__cd6e6a_idx'),
        ),
    ]
