# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysiotherapySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateField(default=django.utils.timezone.localdate)),
                ('treatment_type', models.CharField(max_length=100)),
                ('exercises_performed', models.JSONField(default=list, help_text='[{"name":"","sets":3,"reps":10,"notes":""}]')),
                ('subjective', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('pain_pre', models.IntegerField(blank=True, help_text='0-10 before session.', null=True)),
                ('pain_post', models.IntegerField(blank=True, help_text='0-10 after session.', null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_sessions', to='patients.patient')),
                ('practitioner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_sessions', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'physio_session',
                'ordering': ['-session_date'],
                'indexes': [models.Index(fields=['patient'], name='physio_sess_patient_802d3f_idx'), models.Index(fields=['session_date'], name='physio_sess_session_c666c8_idx')],
            },
        ),
    ]
