# Generated by Django 6.0.7 on 2026-07-25 10:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(help_text='Size in bytes.')),
                ('mime_type', models.CharField(max_length=100)),
                ('storage_path', models.CharField(help_text='Object storage key/path.', max_length=1000)),
                ('file_hash', models.CharField(blank=True, help_text='SHA-256 hash for integrity verification.', max_length=64)),
                ('category', models.CharField(choices=[('consent', 'Consent Form'), ('lab', 'Lab Result'), ('referral', 'Referral Letter'), ('imaging', 'Medical Image'), ('prescription', 'Prescription'), ('invoice', 'Invoice'), ('report', 'Report'), ('insurance', 'Insurance Card'), ('identity', 'ID Document'), ('other', 'Other')], default='other', max_length=30)),
                ('tags', models.JSONField(default=list, help_text='User-defined tags for filtering.')),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_sensitive', models.BooleanField(default=False, help_text='Flag for extra access logging.')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documents_document',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('svg_data', models.TextField(help_text='Raw SVG path data of the signature.')),
                ('entity_type', models.CharField(help_text='e.g., encounter, consent, invoice.', max_length=50)),
                ('entity_id', models.UUIDField()),
                ('signed_by_name', models.CharField(help_text='Name of the signer.', max_length=200)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'documents_signature',
                'ordering': ['-signed_at'],
            },
        ),
    ]
