# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('patients', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='document',
            name='replaces',
            field=models.ForeignKey(blank=True, help_text='Previous version this document replaces.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='documents.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signature',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='signature',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant'], name='documents_d_tenant__c0b07f_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'patient'], name='documents_d_tenant__2430d5_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'category'], name='documents_d_tenant__560fbc_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['storage_path'], name='documents_d_storage_80abc9_idx'),
        ),
        migrations.AddIndex(
            model_name='signature',
            index=models.Index(fields=['tenant'], name='documents_s_tenant__0b354a_idx'),
        ),
        migrations.AddIndex(
            model_name='signature',
            index=models.Index(fields=['entity_type', 'entity_id'], name='documents_s_entity__f9bad8_idx'),
        ),
    ]
