# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudiologyExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_date', models.DateField(default=django.utils.timezone.localdate)),
                ('test_type', models.CharField(choices=[('pure_tone', 'Pure Tone Audiometry'), ('tympanometry', 'Tympanometry'), ('speech', 'Speech Audiometry'), ('oae', 'OAE'), ('abr', 'ABR')], max_length=30)),
                ('thresholds_od', models.JSONField(default=dict, help_text='{"500Hz":15,"1000Hz":20,"2000Hz":25,"4000Hz":30}')),
                ('thresholds_os', models.JSONField(default=dict)),
                ('hearing_loss_type', models.CharField(blank=True, choices=[('normal', 'Normal'), ('conductive', 'Conductive'), ('sensorineural', 'Sensorineural'), ('mixed', 'Mixed')], max_length=30)),
                ('hearing_loss_severity', models.CharField(blank=True, choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('profound', 'Profound')], max_length=20)),
                ('findings', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ent_audiology',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='EndoscopyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('procedure_date', models.DateField(default=django.utils.timezone.localdate)),
                ('endoscopy_type', models.CharField(choices=[('nasal', 'Nasal Endoscopy'), ('laryngeal', 'Laryngoscopy'), ('otoscopic', 'Otoscopy')], max_length=30)),
                ('findings', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('images_paths', models.JSONField(default=list, help_text='List of image file paths.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ent_endoscopy',
                'ordering': ['-procedure_date'],
            },
        ),
    ]
