# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ent', '0001_initial'),
        ('patients', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audiologyexam',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiology_exams', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='audiologyexam',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audiologyexam',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiology_exams', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='endoscopyrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endoscopy_records', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='endoscopyrecord',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='endoscopyrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endoscopy_records', to='tenancy.tenant'),
        ),
    ]
