# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        ('patients', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentalMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age_group', models.CharField(choices=[('2m', '2 Months'), ('4m', '4 Months'), ('6m', '6 Months'), ('9m', '9 Months'), ('12m', '12 Months'), ('18m', '18 Months'), ('2y', '2 Years'), ('3y', '3 Years'), ('4y', '4 Years'), ('5y', '5 Years')], max_length=10)),
                ('domain', models.CharField(choices=[('gross_motor', 'Gross Motor'), ('fine_motor', 'Fine Motor'), ('language', 'Language'), ('social', 'Social-Emotional'), ('cognitive', 'Cognitive')], max_length=20)),
                ('milestone_name', models.CharField(max_length=300)),
                ('is_achieved', models.BooleanField(default=False)),
                ('achieved_date', models.DateField(blank=True, null=True)),
                ('is_delayed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'peds_milestone',
                'ordering': ['age_group', 'domain'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=300)),
                ('recommended_age_months', models.IntegerField(help_text='Age in months when vaccine is recommended.')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('due', 'Due'), ('administered', 'Administered'), ('overdue', 'Overdue'), ('declined', 'Declined'), ('contraindicated', 'Contraindicated')], default='due', max_length=20)),
                ('administered_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vax_schedules', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vax_schedules', to='tenancy.tenant')),
                ('vaccination_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical.vaccination')),
            ],
            options={
                'db_table': 'peds_vax_schedule',
                'ordering': ['recommended_age_months', 'vaccine_name'],
            },
        ),
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measured_date', models.DateField(default=django.utils.timezone.localdate)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('head_circumference_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height_percentile', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weight_percentile', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('bmi_percentile', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='patients.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'peds_growth',
                'ordering': ['-measured_date'],
                'indexes': [models.Index(fields=['patient'], name='peds_growth_patient_c95457_idx'), models.Index(fields=['measured_date'], name='peds_growth_measure_25e79f_idx')],
            },
        ),
    ]
