# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reason', models.TextField(blank=True)),
                ('va_od_unaided', models.CharField(blank=True, help_text='e.g. 20/20', max_length=20)),
                ('va_os_unaided', models.CharField(blank=True, max_length=20)),
                ('va_od_best', models.CharField(blank=True, help_text='Best corrected.', max_length=20)),
                ('va_os_best', models.CharField(blank=True, max_length=20)),
                ('refraction_od_sphere', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('refraction_od_cylinder', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('refraction_od_axis', models.IntegerField(blank=True, null=True)),
                ('refraction_os_sphere', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('refraction_os_cylinder', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('refraction_os_axis', models.IntegerField(blank=True, null=True)),
                ('iop_od', models.IntegerField(blank=True, null=True)),
                ('iop_os', models.IntegerField(blank=True, null=True)),
                ('slit_lamp_findings', models.TextField(blank=True)),
                ('fundus_findings', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_exams', to='patients.patient')),
                ('practitioner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eye_exams', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_exams', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'ophth_exam',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='LensPrescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prescription_type', models.CharField(choices=[('glasses', 'Glasses'), ('contacts', 'Contact Lenses')], default='glasses', max_length=20)),
                ('od_sphere', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('od_cylinder', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('od_axis', models.IntegerField(blank=True, null=True)),
                ('od_add', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('os_sphere', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('os_cylinder', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('os_axis', models.IntegerField(blank=True, null=True)),
                ('os_add', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('pd', models.DecimalField(blank=True, decimal_places=1, help_text='Pupillary distance in mm.', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('prescribed_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ophthalmology.eyeexam')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lens_prescriptions', to='patients.patient')),
                ('prescribed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lens_prescriptions', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'ophth_prescription',
                'ordering': ['-prescribed_date'],
            },
        ),
        migrations.CreateModel(
            name='VisionTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_type', models.CharField(choices=[('color_vision', 'Color Vision'), ('visual_field', 'Visual Field'), ('amsler_grid', 'Amsler Grid'), ('other', 'Other')], max_length=30)),
                ('result_od', models.TextField(blank=True, help_text='Right eye result.')),
                ('result_os', models.TextField(blank=True, help_text='Left eye result.')),
                ('notes', models.TextField(blank=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_tests', to='ophthalmology.eyeexam')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'ophth_vision_test',
            },
        ),
        migrations.AddIndex(
            model_name='eyeexam',
            index=models.Index(fields=['patient'], name='ophth_exam_patient_350ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='eyeexam',
            index=models.Index(fields=['exam_date'], name='ophth_exam_exam_da_0cbbd2_idx'),
        ),
    ]
