# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arrival_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('triage_level', models.IntegerField(choices=[(1, '1 — Immediate'), (2, '2 — Emergent'), (3, '3 — Urgent'), (4, '4 — Semi-Urgent'), (5, '5 — Non-Urgent')], help_text='ESI Triage Level')),
                ('chief_complaint', models.TextField()),
                ('mode_of_arrival', models.CharField(choices=[('self', 'Self/Walk-in'), ('ambulance', 'Ambulance'), ('transfer', 'Transfer')], default='self', max_length=30)),
                ('disposition', models.CharField(blank=True, choices=[('admitted', 'Admitted'), ('discharged', 'Discharged'), ('transferred', 'Transferred'), ('ama', 'Left AMA'), ('expired', 'Expired')], max_length=30)),
                ('disposition_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'er_visit',
                'ordering': ['-arrival_date'],
            },
        ),
    ]
