# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('widget_type', models.CharField(choices=[('appointments_today', "Today's Appointments"), ('revenue_today', "Today's Revenue"), ('new_patients', 'New Patients This Month'), ('pending_invoices', 'Pending Invoices'), ('low_stock', 'Low Stock Alerts'), ('queue_status', 'Queue Status'), ('procedure_mix', 'Procedure Mix'), ('no_show_rate', 'No-Show Rate'), ('custom', 'Custom')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('config', models.JSONField(default=dict, help_text='Widget-specific configuration.')),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=1, help_text='Grid columns (1-4).')),
                ('height', models.IntegerField(default=1)),
                ('module_dependency', models.CharField(blank=True, help_text='Only show if this module is enabled.', max_length=50)),
                ('required_permission', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roles', models.ManyToManyField(blank=True, help_text='Roles that can see this widget. Empty = all roles.', to='identity.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'reporting_dashboard_widget',
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('operational', 'Operational'), ('financial', 'Financial'), ('clinical', 'Clinical')], default='operational', max_length=20)),
                ('report_type', models.CharField(help_text="Identifier for the report logic, e.g. 'appointments_by_day'.", max_length=100)),
                ('parameters_schema', models.JSONField(default=dict, help_text='JSON Schema for report parameters: date_from, date_to, practitioner_id, etc.')),
                ('required_permission', models.CharField(blank=True, help_text='Permission required to run this report.', max_length=100)),
                ('module_dependency', models.CharField(blank=True, help_text="Module that must be enabled, e.g. 'dental'.", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='Null for built-in reports available to all tenants.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_definitions', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'reporting_report_definition',
                'ordering': ['category', 'name'],
            },
        ),
    ]
