# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'derm_body_map',
            },
        ),
        migrations.CreateModel(
            name='DermatologyProcedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('procedure_type', models.CharField(choices=[('excision', 'Excision'), ('biopsy', 'Biopsy'), ('cryotherapy', 'Cryotherapy'), ('curettage', 'Curettage'), ('laser', 'Laser'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('performed_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'derm_procedure',
                'ordering': ['-performed_date'],
            },
        ),
        migrations.CreateModel(
            name='Lesion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Label for this lesion.', max_length=200)),
                ('body_region', models.CharField(choices=[('head', 'Head & Neck'), ('trunk_front', 'Trunk (Anterior)'), ('trunk_back', 'Trunk (Posterior)'), ('arm_left', 'Left Arm'), ('arm_right', 'Right Arm'), ('hand_left', 'Left Hand'), ('hand_right', 'Right Hand'), ('leg_left', 'Left Leg'), ('leg_right', 'Right Leg'), ('foot_left', 'Left Foot'), ('foot_right', 'Right Foot'), ('other', 'Other')], default='other', max_length=20)),
                ('location_detail', models.CharField(blank=True, help_text='Specific anatomical location.', max_length=300)),
                ('size_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('morphology', models.CharField(blank=True, help_text='Macule, papule, nodule, plaque, etc.', max_length=200)),
                ('border', models.CharField(blank=True, max_length=100)),
                ('dermoscopy_findings', models.TextField(blank=True)),
                ('clinical_impression', models.TextField(blank=True, help_text='Likely diagnosis.')),
                ('is_biopsied', models.BooleanField(default=False)),
                ('biopsy_result', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('discovered_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'derm_lesion',
                'ordering': ['body_region', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LesionPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_path', models.CharField(help_text='Object storage path.', max_length=1000)),
                ('taken_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('dermoscopy', models.BooleanField(default=False, help_text='Taken with dermoscope.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'derm_lesion_photo',
                'ordering': ['-taken_date'],
            },
        ),
    ]
