# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dermatology', '0001_initial'),
        ('patients', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bodymap',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='body_map', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='bodymap',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_maps', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='dermatologyprocedure',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derm_procedures', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='dermatologyprocedure',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dermatologyprocedure',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derm_procedures', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='lesion',
            name='body_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesions', to='dermatology.bodymap'),
        ),
        migrations.AddField(
            model_name='lesion',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesions', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='lesion',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesion',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='dermatologyprocedure',
            name='lesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='dermatology.lesion'),
        ),
        migrations.AddField(
            model_name='lesionphoto',
            name='lesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='dermatology.lesion'),
        ),
        migrations.AddField(
            model_name='lesionphoto',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='lesion',
            index=models.Index(fields=['patient'], name='derm_lesion_patient_3956b1_idx'),
        ),
        migrations.AddIndex(
            model_name='lesion',
            index=models.Index(fields=['body_region'], name='derm_lesion_body_re_fa03cc_idx'),
        ),
    ]
