# Generated by Django 6.0.7 on 2026-07-25 10:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_display', models.CharField(blank=True, help_text='Snapshot of actor name at time of action.', max_length=200)),
                ('session_id', models.CharField(blank=True, default='', max_length=100)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', help_text='Links related audit events.', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('entity_type', models.CharField(db_index=True, help_text="Model or resource type, e.g. 'Patient', 'Invoice'.", max_length=100)),
                ('entity_id', models.CharField(blank=True, db_index=True, help_text='UUID or identifier of the affected entity.', max_length=100)),
                ('entity_display', models.CharField(blank=True, help_text='Human-readable label for the entity.', max_length=300)),
                ('action', models.CharField(db_index=True, help_text='create, update, delete, read, login, logout, export, etc.', max_length=100)),
                ('before_value', models.JSONField(blank=True, null=True)),
                ('after_value', models.JSONField(blank=True, null=True)),
                ('is_sensitive', models.BooleanField(default=False, help_text='Marks events on sensitive data for extra retention.')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'audit_event',
                'ordering': ['-created_at'],
            },
        ),
    ]
