# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEdition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('solo', 'Solo Clinic'), ('specialist', 'Specialist Pro'), ('diagnostic', 'Diagnostic Center'), ('polyclinic', 'Polyclinic'), ('hospital', 'Hospital Network')], max_length=50, unique=True)),
                ('max_users', models.IntegerField(default=5)),
                ('max_patients', models.IntegerField(default=0, help_text='0 = unlimited.')),
                ('max_branches', models.IntegerField(default=1)),
                ('enabled_modules', models.JSONField(default=list, help_text='Default modules for this edition.')),
                ('features', models.JSONField(default=dict, help_text='Feature flags: {telehealth: true, ai_assistant: false, fhir_api: false, white_label: false}')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tenancy_edition',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text="Unique URL-safe identifier, e.g. 'smile-dental-clinic'.", max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='Slug must be lowercase letters, numbers, and hyphens only.', regex='^[a-z0-9-]+$')])),
                ('name', models.CharField(help_text="Display name, e.g. 'Smile Dental Clinic'.", max_length=200)),
                ('branding', models.JSONField(blank=True, default=dict, help_text='White-label branding tokens.')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Per-tenant configuration.')),
                ('enabled_modules', models.JSONField(blank=True, default=list, help_text='List of enabled module names.')),
                ('custom_domain', models.CharField(blank=True, help_text="Custom domain for white-label, e.g. 'app.smileclinic.com'.", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive tenants cannot be accessed.')),
                ('subscription_plan', models.CharField(blank=True, max_length=100)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled')], default='active', max_length=50)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenancy_tenant',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='tenancy_ten_slug_46265a_idx'), models.Index(fields=['custom_domain'], name='tenancy_ten_custom__62c5b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompliancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clinical_record_retention_days', models.IntegerField(default=3650, help_text='10 years default.')),
                ('billing_record_retention_days', models.IntegerField(default=2555, help_text='7 years default.')),
                ('audit_log_retention_days', models.IntegerField(default=2555)),
                ('require_signature_on_prescriptions', models.BooleanField(default=True)),
                ('require_signature_on_encounters', models.BooleanField(default=True)),
                ('require_signature_on_consents', models.BooleanField(default=True)),
                ('consent_required_for_treatment', models.BooleanField(default=True)),
                ('consent_required_for_data_sharing', models.BooleanField(default=True)),
                ('consent_required_for_telehealth', models.BooleanField(default=True)),
                ('consent_expiry_days', models.IntegerField(default=365, help_text='Consents expire after this many days.')),
                ('max_refills_per_prescription', models.IntegerField(default=12)),
                ('prescription_expiry_days', models.IntegerField(default=365)),
                ('require_pdmp_check', models.BooleanField(default=False, help_text='Check PDMP before prescribing controlled substances.')),
                ('allow_patient_data_export', models.BooleanField(default=True)),
                ('export_format', models.CharField(choices=[('fhir', 'FHIR'), ('csv', 'CSV'), ('pdf', 'PDF')], default='fhir', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_policy', to='tenancy.tenant')),
            ],
            options={
                'verbose_name_plural': 'compliance policies',
                'db_table': 'tenancy_compliance',
            },
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=False)),
                ('appointment_reminder_hours', models.JSONField(default=list, help_text='Hours before appointment to send reminders.')),
                ('default_appointment_duration_minutes', models.IntegerField(default=30)),
                ('allow_online_booking', models.BooleanField(default=True)),
                ('booking_advance_days', models.IntegerField(default=30, help_text='How many days in advance patients can book.')),
                ('billing_grace_period_days', models.IntegerField(default=30)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('tax_rate_default', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('invoice_prefix', models.CharField(default='INV-', max_length=10)),
                ('invoice_footer', models.TextField(blank=True)),
                ('prescription_footer', models.TextField(blank=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='MM/DD/YYYY', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('mfa_required_for_roles', models.JSONField(blank=True, default=list, help_text='List of role names that require MFA.')),
                ('session_timeout_minutes', models.IntegerField(default=240)),
                ('max_failed_login_attempts', models.IntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_settings', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'tenant settings',
                'verbose_name_plural': 'tenant settings',
                'db_table': 'tenancy_settings',
            },
        ),
        migrations.CreateModel(
            name='OnboardingStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_name', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_steps', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'tenancy_onboarding',
                'ordering': ['display_order'],
                'unique_together': {('tenant', 'step_name')},
            },
        ),
    ]
