# Generated by Django 6.0.7 on 2026-07-25 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('patients', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=300)),
                ('drug_code', models.CharField(blank=True, help_text='NDC or DIN code.', max_length=50)),
                ('dosage', models.CharField(help_text='e.g. 500mg', max_length=100)),
                ('frequency', models.CharField(help_text='e.g. TID, QID, q6h', max_length=100)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('sublingual', 'Sublingual'), ('topical', 'Topical'), ('inhaled', 'Inhaled'), ('iv', 'Intravenous'), ('im', 'Intramuscular'), ('sc', 'Subcutaneous'), ('rectal', 'Rectal'), ('ophthalmic', 'Ophthalmic'), ('otic', 'Otic'), ('other', 'Other')], default='oral', max_length=20)),
                ('instructions', models.TextField(blank=True, help_text='Sig: take with food, etc.')),
                ('quantity_prescribed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_dispensed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refills_authorized', models.IntegerField(default=0)),
                ('refills_used', models.IntegerField(default=0)),
                ('daw', models.BooleanField(default=False, help_text='Dispense as written — no substitution.')),
                ('is_controlled', models.BooleanField(default=False)),
                ('controlled_schedule', models.CharField(blank=True, choices=[('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partially_filled', 'Partially Filled'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=25)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Prescription expires on this date.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(blank=True, help_text='Encounter where this was prescribed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='scheduling.appointment')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='inventory.inventoryitem')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='patients.patient')),
                ('prescribed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'pharmacy_prescription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispenseRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('copay_charged', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_refill', models.BooleanField(default=False)),
                ('refill_number', models.IntegerField(default=0)),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispense_records', to='inventory.batch')),
                ('dispensed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispensed', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispense_records', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispense_records', to='tenancy.tenant')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispense_records', to='pharmacy.prescription')),
            ],
            options={
                'db_table': 'pharmacy_dispense',
                'ordering': ['-dispensed_at'],
            },
        ),
        migrations.CreateModel(
            name='ControlledSubstanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('witness_signature', models.TextField(blank=True, help_text='SVG signature data.')),
                ('quantity_before_dispense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_after_dispense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('count_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlled_logs', to='tenancy.tenant')),
                ('witness', models.ForeignKey(blank=True, help_text='Required for Schedule II.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='witnessed_dispenses', to=settings.AUTH_USER_MODEL)),
                ('dispense_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='controlled_log', to='pharmacy.dispenserecord')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlled_logs', to='pharmacy.prescription')),
            ],
            options={
                'db_table': 'pharmacy_controlled_log',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['tenant'], name='pharmacy_pr_tenant__889d38_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient'], name='pharmacy_pr_patient_193714_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status'], name='pharmacy_pr_status_3f9cad_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['is_controlled'], name='pharmacy_pr_is_cont_bb07ae_idx'),
        ),
        migrations.AddIndex(
            model_name='dispenserecord',
            index=models.Index(fields=['tenant'], name='pharmacy_di_tenant__24bc40_idx'),
        ),
        migrations.AddIndex(
            model_name='dispenserecord',
            index=models.Index(fields=['prescription'], name='pharmacy_di_prescri_2ad925_idx'),
        ),
    ]
